version: "3.4"
services:
  forecasts:
    image: forecasts:prod
    build:
      context: forecasts
      dockerfile: Dockerfile.prod
      args:
        SECRET_KEY: ${SECRET_KEY}
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres:
