version: "3.4"
services:
  forecasts:
    image: forecasts:dev
    build:
      dockerfile: Dockerfile.dev
      args:
        OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}
    volumes:
      - ./forecasts:/project
    ports:
      - 3001:3001
